version: '2'

services:
  apollo-quick-start:
    image: lijasonvip/apollo-quick-start:1.1
    container_name: apollo-quick-start
    depends_on:
      - apollo-db
    ports:
      - "8080:8080"
      - "8070:8070"
    links:
      - apollo-db

  apollo-db:
    image: lijasonvip/apollodb:1.2
    container_name: apollo-db
    ports:
      - "13306:3306"
